"use client"
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const SOCIAL_LOGIN_REQUEST = "SOCIAL_LOGIN_REQUEST";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS ";
export const SOCIAL_LOGIN_FAIL = "SOCIAL_LOGIN_FAIL";


export const POST_ADDRESS_REQUEST = "POST_ADDRESS_REQUEST";
export const POST_ADDRESS_SUCCESS = "POST_ADDRESS_SUCCESS ";
export const POST_ADDRESS_FAIL = "POST_ADDRESS_FAIL";

export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS ";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS ";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const COMPLETED_ORDERS_REQUEST = "COMPLETED_ORDERS_REQUEST";
export const COMPLETED_ORDERS_SUCCESS = "COMPLETED_ORDERS_SUCCESS ";
export const COMPLETED_ORDERS_FAIL = "COMPLETED_ORDERS_FAIL";

export const ONGOING_ORDERS_REQUEST = "ONGOING_ORDERS_REQUEST";
export const ONGOING_ORDERS_SUCCESS = "ONGOING_ORDERS_SUCCESS ";
export const ONGOING_ORDERS_FAIL = "ONGOING_ORDERS_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS ";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";